import type { Metadata } from "next";

import "./index.css";

import React from 'react'
import localFont from "next/font/local";

const pretendard = localFont({
    src: "../assets/fonts/PretendardVariable.woff2", // 폰트 파일 경로를 지정합니다.
    display: "swap",
    variable: "--font-pretendard", // CSS 변수 이름을 지정합니다.
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${pretendard.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
